# Generated by Django 2.1.7 on 2019-02-27 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=255)),
                ('symbol', models.TextField(max_length=10)),
                ('address', models.TextField(max_length=255)),
                ('state', models.TextField(max_length=2)),
                ('zip', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('symbol', models.TextField(max_length=10)),
                ('buy_order', models.BooleanField()),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
